### ISSUE TITLE
tgxm model viewer canceld?

### ISSUE THREAD

**Issue by Kurainu** [GoomiiV2/Destiny-tgxm-model-viewer#2]
is the model viewer canceld or you simple have no time to do it (not good grammar xD) @GoomiChan

**Comment by GoomiiV2** [comment]
Yea, I sorta lost interest in taking it any further, the file formats are fairly simple at least.

**Comment by Kurainu** [comment]
I am sorry because my would modding project helped. I would be delighted if you could a simple viewer with textures and make export.
I would even if you give you something as a small "thank you"
I would appreciate an answer
sry for my bad english @GoomiChan

**Comment by Kurainu** [comment]
and so whats are your decision? @GoomiChan

**Comment by Kurainu** [comment]
could I please get an answer ? @GoomiChan

**Comment by GoomiiV2** [comment]
Sorry I have been very busy lately, I just won't have the time to do anything with this.
